// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/devices.dart';
import 'api/download.dart';
import 'api/engine.dart';
import 'api/model.dart';
import 'api/settings.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  RustStreamSink<DownloadEventDto> dco_decode_StreamSink_download_event_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<InstallProgressDto>
  dco_decode_StreamSink_install_progress_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<TranscribeEventDto>
  dco_decode_StreamSink_transcribe_event_dto_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BackendDto dco_decode_backend_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DownloadProgressDto dco_decode_box_autoadd_download_progress_dto(dynamic raw);

  @protected
  SettingsDto dco_decode_box_autoadd_settings_dto(dynamic raw);

  @protected
  DownloadEventDto dco_decode_download_event_dto(dynamic raw);

  @protected
  DownloadProgressDto dco_decode_download_progress_dto(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GpuDeviceDto dco_decode_gpu_device_dto(dynamic raw);

  @protected
  InstallProgressDto dco_decode_install_progress_dto(dynamic raw);

  @protected
  List<BackendDto> dco_decode_list_backend_dto(dynamic raw);

  @protected
  List<GpuDeviceDto> dco_decode_list_gpu_device_dto(dynamic raw);

  @protected
  List<ModelPathDto> dco_decode_list_model_path_dto(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<TranscriptLineDto> dco_decode_list_transcript_line_dto(dynamic raw);

  @protected
  LoadedProjectDto dco_decode_loaded_project_dto(dynamic raw);

  @protected
  ModelPathDto dco_decode_model_path_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DownloadProgressDto? dco_decode_opt_box_autoadd_download_progress_dto(
    dynamic raw,
  );

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  SettingsDto dco_decode_settings_dto(dynamic raw);

  @protected
  SystemInfoDto dco_decode_system_info_dto(dynamic raw);

  @protected
  TranscribeEventDto dco_decode_transcribe_event_dto(dynamic raw);

  @protected
  TranscriptLineDto dco_decode_transcript_line_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<DownloadEventDto> sse_decode_StreamSink_download_event_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<InstallProgressDto>
  sse_decode_StreamSink_install_progress_dto_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<TranscribeEventDto>
  sse_decode_StreamSink_transcribe_event_dto_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BackendDto sse_decode_backend_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DownloadProgressDto sse_decode_box_autoadd_download_progress_dto(
    SseDeserializer deserializer,
  );

  @protected
  SettingsDto sse_decode_box_autoadd_settings_dto(SseDeserializer deserializer);

  @protected
  DownloadEventDto sse_decode_download_event_dto(SseDeserializer deserializer);

  @protected
  DownloadProgressDto sse_decode_download_progress_dto(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GpuDeviceDto sse_decode_gpu_device_dto(SseDeserializer deserializer);

  @protected
  InstallProgressDto sse_decode_install_progress_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<BackendDto> sse_decode_list_backend_dto(SseDeserializer deserializer);

  @protected
  List<GpuDeviceDto> sse_decode_list_gpu_device_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ModelPathDto> sse_decode_list_model_path_dto(
    SseDeserializer deserializer,
  );

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<TranscriptLineDto> sse_decode_list_transcript_line_dto(
    SseDeserializer deserializer,
  );

  @protected
  LoadedProjectDto sse_decode_loaded_project_dto(SseDeserializer deserializer);

  @protected
  ModelPathDto sse_decode_model_path_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DownloadProgressDto? sse_decode_opt_box_autoadd_download_progress_dto(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  SettingsDto sse_decode_settings_dto(SseDeserializer deserializer);

  @protected
  SystemInfoDto sse_decode_system_info_dto(SseDeserializer deserializer);

  @protected
  TranscribeEventDto sse_decode_transcribe_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  TranscriptLineDto sse_decode_transcript_line_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_download_event_dto_Sse(
    RustStreamSink<DownloadEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_install_progress_dto_Sse(
    RustStreamSink<InstallProgressDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_transcribe_event_dto_Sse(
    RustStreamSink<TranscribeEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_backend_dto(BackendDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_download_progress_dto(
    DownloadProgressDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_settings_dto(
    SettingsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_download_event_dto(
    DownloadEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_download_progress_dto(
    DownloadProgressDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_gpu_device_dto(GpuDeviceDto self, SseSerializer serializer);

  @protected
  void sse_encode_install_progress_dto(
    InstallProgressDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_backend_dto(
    List<BackendDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_gpu_device_dto(
    List<GpuDeviceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_model_path_dto(
    List<ModelPathDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transcript_line_dto(
    List<TranscriptLineDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_loaded_project_dto(
    LoadedProjectDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_model_path_dto(ModelPathDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_download_progress_dto(
    DownloadProgressDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_settings_dto(SettingsDto self, SseSerializer serializer);

  @protected
  void sse_encode_system_info_dto(SystemInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_transcribe_event_dto(
    TranscribeEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transcript_line_dto(
    TranscriptLineDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
