// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/devices.dart';
import 'api/download.dart';
import 'api/engine.dart';
import 'api/model.dart';
import 'api/settings.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 914599592;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'asr_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<bool> crateApiEngineAlignerModelAvailable();

  Future<void> crateApiDownloadCancelDownload();

  Future<void> crateApiEngineCancelLoad();

  Future<void> crateApiEngineConvertModelToQ8();

  Future<bool> crateApiEngineDiarModelAvailable();

  Stream<DownloadEventDto> crateApiDownloadDownloadModel({
    required String source,
  });

  Stream<InstallProgressDto> crateApiEngineInstallAlignerModel();

  Stream<InstallProgressDto> crateApiEngineInstallDiarModel();

  Future<bool> crateApiEngineIsModelLoaded();

  Future<String> crateApiEngineLastLrc();

  Future<String> crateApiEngineLastSrt();

  Future<void> crateApiEngineLoadModel({
    required String backend,
    required int deviceOrdinal,
  });

  Future<LoadedProjectDto> crateApiEngineLoadProject({required String path});

  Future<SettingsDto> crateApiSettingsLoadSettings();

  Future<String> crateApiModelModelDirPath();

  Future<bool> crateApiModelModelIsOnDisk();

  Future<List<ModelPathDto>> crateApiModelModelPaths();

  Future<List<TranscriptLineDto>> crateApiEngineOriginalTranscriptLines();

  Future<String> crateApiEnginePolishText({required String text});

  Future<void> crateApiEnginePushProofSnapshot();

  Future<bool> crateApiEngineQ8ModelAvailable();

  Future<int> crateApiEngineRealignProjectLines();

  Future<void> crateApiEngineSaveProject({required String path});

  Future<void> crateApiSettingsSaveSettings({required SettingsDto dto});

  Future<void> crateApiEngineSetSpeakerName({
    required String speaker,
    required String name,
  });

  Future<Map<String, String>> crateApiEngineSpeakerNamesMap();

  Future<void> crateApiEngineSplitTranscriptLine({
    required int index,
    required int charPos,
    String? secondSpeaker,
  });

  Future<void> crateApiEngineStopTranscribe();

  Future<SystemInfoDto> crateApiDevicesSystemInfo();

  Stream<TranscribeEventDto> crateApiEngineTranscribeFile({
    required String path,
    required String language,
  });

  Future<List<TranscriptLineDto>> crateApiEngineTranscriptLines();

  Future<bool> crateApiEngineUndoProofEdit();

  Future<void> crateApiEngineUnloadModel();

  Future<void> crateApiEngineUpdateLineSpeaker({
    required int index,
    String? speaker,
  });

  Future<void> crateApiEngineUpdateProjectAudio({required String path});

  Future<void> crateApiEngineUpdateTranscriptLine({
    required int index,
    required String text,
  });

  Future<Float32List> crateApiEngineWaveformPeaks({
    required String path,
    required int bucketsPerSec,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiEngineAlignerModelAvailable() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineAlignerModelAvailableConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineAlignerModelAvailableConstMeta =>
      const TaskConstMeta(debugName: "aligner_model_available", argNames: []);

  @override
  Future<void> crateApiDownloadCancelDownload() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDownloadCancelDownloadConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadCancelDownloadConstMeta =>
      const TaskConstMeta(debugName: "cancel_download", argNames: []);

  @override
  Future<void> crateApiEngineCancelLoad() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineCancelLoadConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineCancelLoadConstMeta =>
      const TaskConstMeta(debugName: "cancel_load", argNames: []);

  @override
  Future<void> crateApiEngineConvertModelToQ8() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineConvertModelToQ8ConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineConvertModelToQ8ConstMeta =>
      const TaskConstMeta(debugName: "convert_model_to_q8", argNames: []);

  @override
  Future<bool> crateApiEngineDiarModelAvailable() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineDiarModelAvailableConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineDiarModelAvailableConstMeta =>
      const TaskConstMeta(debugName: "diar_model_available", argNames: []);

  @override
  Stream<DownloadEventDto> crateApiDownloadDownloadModel({
    required String source,
  }) {
    final sink = RustStreamSink<DownloadEventDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(source, serializer);
            sse_encode_StreamSink_download_event_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 6,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiDownloadDownloadModelConstMeta,
          argValues: [source, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDownloadDownloadModelConstMeta =>
      const TaskConstMeta(
        debugName: "download_model",
        argNames: ["source", "sink"],
      );

  @override
  Stream<InstallProgressDto> crateApiEngineInstallAlignerModel() {
    final sink = RustStreamSink<InstallProgressDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_install_progress_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 7,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiEngineInstallAlignerModelConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiEngineInstallAlignerModelConstMeta =>
      const TaskConstMeta(
        debugName: "install_aligner_model",
        argNames: ["sink"],
      );

  @override
  Stream<InstallProgressDto> crateApiEngineInstallDiarModel() {
    final sink = RustStreamSink<InstallProgressDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_install_progress_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 8,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiEngineInstallDiarModelConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiEngineInstallDiarModelConstMeta =>
      const TaskConstMeta(debugName: "install_diar_model", argNames: ["sink"]);

  @override
  Future<bool> crateApiEngineIsModelLoaded() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineIsModelLoadedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineIsModelLoadedConstMeta =>
      const TaskConstMeta(debugName: "is_model_loaded", argNames: []);

  @override
  Future<String> crateApiEngineLastLrc() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineLastLrcConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineLastLrcConstMeta =>
      const TaskConstMeta(debugName: "last_lrc", argNames: []);

  @override
  Future<String> crateApiEngineLastSrt() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineLastSrtConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineLastSrtConstMeta =>
      const TaskConstMeta(debugName: "last_srt", argNames: []);

  @override
  Future<void> crateApiEngineLoadModel({
    required String backend,
    required int deviceOrdinal,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(backend, serializer);
          sse_encode_u_32(deviceOrdinal, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineLoadModelConstMeta,
        argValues: [backend, deviceOrdinal],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineLoadModelConstMeta => const TaskConstMeta(
    debugName: "load_model",
    argNames: ["backend", "deviceOrdinal"],
  );

  @override
  Future<LoadedProjectDto> crateApiEngineLoadProject({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_loaded_project_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineLoadProjectConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineLoadProjectConstMeta =>
      const TaskConstMeta(debugName: "load_project", argNames: ["path"]);

  @override
  Future<SettingsDto> crateApiSettingsLoadSettings() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_settings_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSettingsLoadSettingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsLoadSettingsConstMeta =>
      const TaskConstMeta(debugName: "load_settings", argNames: []);

  @override
  Future<String> crateApiModelModelDirPath() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelModelDirPathConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelModelDirPathConstMeta =>
      const TaskConstMeta(debugName: "model_dir_path", argNames: []);

  @override
  Future<bool> crateApiModelModelIsOnDisk() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelModelIsOnDiskConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelModelIsOnDiskConstMeta =>
      const TaskConstMeta(debugName: "model_is_on_disk", argNames: []);

  @override
  Future<List<ModelPathDto>> crateApiModelModelPaths() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_model_path_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelModelPathsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelModelPathsConstMeta =>
      const TaskConstMeta(debugName: "model_paths", argNames: []);

  @override
  Future<List<TranscriptLineDto>> crateApiEngineOriginalTranscriptLines() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_transcript_line_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineOriginalTranscriptLinesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineOriginalTranscriptLinesConstMeta =>
      const TaskConstMeta(debugName: "original_transcript_lines", argNames: []);

  @override
  Future<String> crateApiEnginePolishText({required String text}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEnginePolishTextConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnginePolishTextConstMeta =>
      const TaskConstMeta(debugName: "polish_text", argNames: ["text"]);

  @override
  Future<void> crateApiEnginePushProofSnapshot() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEnginePushProofSnapshotConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnginePushProofSnapshotConstMeta =>
      const TaskConstMeta(debugName: "push_proof_snapshot", argNames: []);

  @override
  Future<bool> crateApiEngineQ8ModelAvailable() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineQ8ModelAvailableConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineQ8ModelAvailableConstMeta =>
      const TaskConstMeta(debugName: "q8_model_available", argNames: []);

  @override
  Future<int> crateApiEngineRealignProjectLines() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineRealignProjectLinesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineRealignProjectLinesConstMeta =>
      const TaskConstMeta(debugName: "realign_project_lines", argNames: []);

  @override
  Future<void> crateApiEngineSaveProject({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineSaveProjectConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineSaveProjectConstMeta =>
      const TaskConstMeta(debugName: "save_project", argNames: ["path"]);

  @override
  Future<void> crateApiSettingsSaveSettings({required SettingsDto dto}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_settings_dto(dto, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSettingsSaveSettingsConstMeta,
        argValues: [dto],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsSaveSettingsConstMeta =>
      const TaskConstMeta(debugName: "save_settings", argNames: ["dto"]);

  @override
  Future<void> crateApiEngineSetSpeakerName({
    required String speaker,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(speaker, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineSetSpeakerNameConstMeta,
        argValues: [speaker, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineSetSpeakerNameConstMeta =>
      const TaskConstMeta(
        debugName: "set_speaker_name",
        argNames: ["speaker", "name"],
      );

  @override
  Future<Map<String, String>> crateApiEngineSpeakerNamesMap() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_Map_String_String_None,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineSpeakerNamesMapConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineSpeakerNamesMapConstMeta =>
      const TaskConstMeta(debugName: "speaker_names_map", argNames: []);

  @override
  Future<void> crateApiEngineSplitTranscriptLine({
    required int index,
    required int charPos,
    String? secondSpeaker,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(index, serializer);
          sse_encode_u_32(charPos, serializer);
          sse_encode_opt_String(secondSpeaker, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineSplitTranscriptLineConstMeta,
        argValues: [index, charPos, secondSpeaker],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineSplitTranscriptLineConstMeta =>
      const TaskConstMeta(
        debugName: "split_transcript_line",
        argNames: ["index", "charPos", "secondSpeaker"],
      );

  @override
  Future<void> crateApiEngineStopTranscribe() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineStopTranscribeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineStopTranscribeConstMeta =>
      const TaskConstMeta(debugName: "stop_transcribe", argNames: []);

  @override
  Future<SystemInfoDto> crateApiDevicesSystemInfo() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_system_info_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDevicesSystemInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDevicesSystemInfoConstMeta =>
      const TaskConstMeta(debugName: "system_info", argNames: []);

  @override
  Stream<TranscribeEventDto> crateApiEngineTranscribeFile({
    required String path,
    required String language,
  }) {
    final sink = RustStreamSink<TranscribeEventDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(path, serializer);
            sse_encode_String(language, serializer);
            sse_encode_StreamSink_transcribe_event_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 30,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiEngineTranscribeFileConstMeta,
          argValues: [path, language, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiEngineTranscribeFileConstMeta =>
      const TaskConstMeta(
        debugName: "transcribe_file",
        argNames: ["path", "language", "sink"],
      );

  @override
  Future<List<TranscriptLineDto>> crateApiEngineTranscriptLines() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_transcript_line_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineTranscriptLinesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineTranscriptLinesConstMeta =>
      const TaskConstMeta(debugName: "transcript_lines", argNames: []);

  @override
  Future<bool> crateApiEngineUndoProofEdit() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineUndoProofEditConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineUndoProofEditConstMeta =>
      const TaskConstMeta(debugName: "undo_proof_edit", argNames: []);

  @override
  Future<void> crateApiEngineUnloadModel() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineUnloadModelConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineUnloadModelConstMeta =>
      const TaskConstMeta(debugName: "unload_model", argNames: []);

  @override
  Future<void> crateApiEngineUpdateLineSpeaker({
    required int index,
    String? speaker,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(index, serializer);
          sse_encode_opt_String(speaker, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineUpdateLineSpeakerConstMeta,
        argValues: [index, speaker],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineUpdateLineSpeakerConstMeta =>
      const TaskConstMeta(
        debugName: "update_line_speaker",
        argNames: ["index", "speaker"],
      );

  @override
  Future<void> crateApiEngineUpdateProjectAudio({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineUpdateProjectAudioConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineUpdateProjectAudioConstMeta =>
      const TaskConstMeta(
        debugName: "update_project_audio",
        argNames: ["path"],
      );

  @override
  Future<void> crateApiEngineUpdateTranscriptLine({
    required int index,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(index, serializer);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineUpdateTranscriptLineConstMeta,
        argValues: [index, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineUpdateTranscriptLineConstMeta =>
      const TaskConstMeta(
        debugName: "update_transcript_line",
        argNames: ["index", "text"],
      );

  @override
  Future<Float32List> crateApiEngineWaveformPeaks({
    required String path,
    required int bucketsPerSec,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_u_32(bucketsPerSec, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWaveformPeaksConstMeta,
        argValues: [path, bucketsPerSec],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWaveformPeaksConstMeta =>
      const TaskConstMeta(
        debugName: "waveform_peaks",
        argNames: ["path", "bucketsPerSec"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_string(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  RustStreamSink<DownloadEventDto> dco_decode_StreamSink_download_event_dto_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<InstallProgressDto>
  dco_decode_StreamSink_install_progress_dto_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<TranscribeEventDto>
  dco_decode_StreamSink_transcribe_event_dto_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BackendDto dco_decode_backend_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BackendDto(
      id: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      available: dco_decode_bool(arr[2]),
      note: dco_decode_String(arr[3]),
      devices: dco_decode_list_gpu_device_dto(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DownloadProgressDto dco_decode_box_autoadd_download_progress_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_download_progress_dto(raw);
  }

  @protected
  SettingsDto dco_decode_box_autoadd_settings_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_settings_dto(raw);
  }

  @protected
  DownloadEventDto dco_decode_download_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DownloadEventDto(
      progress: dco_decode_opt_box_autoadd_download_progress_dto(arr[0]),
      error: dco_decode_opt_String(arr[1]),
      cancelled: dco_decode_bool(arr[2]),
    );
  }

  @protected
  DownloadProgressDto dco_decode_download_progress_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return DownloadProgressDto(
      completedFiles: dco_decode_u_32(arr[0]),
      totalFiles: dco_decode_u_32(arr[1]),
      completedBytes: dco_decode_u_64(arr[2]),
      totalBytes: dco_decode_u_64(arr[3]),
      currentFile: dco_decode_String(arr[4]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GpuDeviceDto dco_decode_gpu_device_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return GpuDeviceDto(
      ordinal: dco_decode_u_32(arr[0]),
      name: dco_decode_String(arr[1]),
      memoryBytes: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  InstallProgressDto dco_decode_install_progress_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return InstallProgressDto(
      completedBytes: dco_decode_u_64(arr[0]),
      totalBytes: dco_decode_u_64(arr[1]),
      error: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  List<BackendDto> dco_decode_list_backend_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_backend_dto).toList();
  }

  @protected
  List<GpuDeviceDto> dco_decode_list_gpu_device_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_gpu_device_dto).toList();
  }

  @protected
  List<ModelPathDto> dco_decode_list_model_path_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_model_path_dto).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  List<TranscriptLineDto> dco_decode_list_transcript_line_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_transcript_line_dto).toList();
  }

  @protected
  LoadedProjectDto dco_decode_loaded_project_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LoadedProjectDto(
      audioPath: dco_decode_String(arr[0]),
      audioExists: dco_decode_bool(arr[1]),
      lineCount: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  ModelPathDto dco_decode_model_path_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ModelPathDto(
      label: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      present: dco_decode_bool(arr[2]),
      optional: dco_decode_bool(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  DownloadProgressDto? dco_decode_opt_box_autoadd_download_progress_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_download_progress_dto(raw);
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  SettingsDto dco_decode_settings_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return SettingsDto(
      source: dco_decode_String(arr[0]),
      language: dco_decode_String(arr[1]),
      backend: dco_decode_String(arr[2]),
      deviceOrdinal: dco_decode_u_32(arr[3]),
      acppQ8: dco_decode_bool(arr[4]),
      diarization: dco_decode_bool(arr[5]),
      diarSpeakers: dco_decode_u_32(arr[6]),
      llmPolish: dco_decode_bool(arr[7]),
      llmUrl: dco_decode_String(arr[8]),
      llmKey: dco_decode_String(arr[9]),
      llmModel: dco_decode_String(arr[10]),
      mirrorBase: dco_decode_String(arr[11]),
      proxy: dco_decode_String(arr[12]),
    );
  }

  @protected
  SystemInfoDto dco_decode_system_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SystemInfoDto(
      totalMemoryBytes: dco_decode_u_64(arr[0]),
      cpuCount: dco_decode_u_32(arr[1]),
      cpuBrand: dco_decode_String(arr[2]),
      backends: dco_decode_list_backend_dto(arr[3]),
    );
  }

  @protected
  TranscribeEventDto dco_decode_transcribe_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return TranscribeEventDto(
      text: dco_decode_opt_String(arr[0]),
      status: dco_decode_opt_String(arr[1]),
      error: dco_decode_opt_String(arr[2]),
      cancelled: dco_decode_bool(arr[3]),
      done: dco_decode_bool(arr[4]),
      language: dco_decode_String(arr[5]),
      elapsedSec: dco_decode_f_64(arr[6]),
    );
  }

  @protected
  TranscriptLineDto dco_decode_transcript_line_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TranscriptLineDto(
      startSec: dco_decode_f_64(arr[0]),
      endSec: dco_decode_f_64(arr[1]),
      speaker: dco_decode_opt_String(arr[2]),
      text: dco_decode_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  RustStreamSink<DownloadEventDto> sse_decode_StreamSink_download_event_dto_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<InstallProgressDto>
  sse_decode_StreamSink_install_progress_dto_Sse(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<TranscribeEventDto>
  sse_decode_StreamSink_transcribe_event_dto_Sse(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BackendDto sse_decode_backend_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_available = sse_decode_bool(deserializer);
    var var_note = sse_decode_String(deserializer);
    var var_devices = sse_decode_list_gpu_device_dto(deserializer);
    return BackendDto(
      id: var_id,
      label: var_label,
      available: var_available,
      note: var_note,
      devices: var_devices,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DownloadProgressDto sse_decode_box_autoadd_download_progress_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_download_progress_dto(deserializer));
  }

  @protected
  SettingsDto sse_decode_box_autoadd_settings_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_settings_dto(deserializer));
  }

  @protected
  DownloadEventDto sse_decode_download_event_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_progress = sse_decode_opt_box_autoadd_download_progress_dto(
      deserializer,
    );
    var var_error = sse_decode_opt_String(deserializer);
    var var_cancelled = sse_decode_bool(deserializer);
    return DownloadEventDto(
      progress: var_progress,
      error: var_error,
      cancelled: var_cancelled,
    );
  }

  @protected
  DownloadProgressDto sse_decode_download_progress_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_completedFiles = sse_decode_u_32(deserializer);
    var var_totalFiles = sse_decode_u_32(deserializer);
    var var_completedBytes = sse_decode_u_64(deserializer);
    var var_totalBytes = sse_decode_u_64(deserializer);
    var var_currentFile = sse_decode_String(deserializer);
    return DownloadProgressDto(
      completedFiles: var_completedFiles,
      totalFiles: var_totalFiles,
      completedBytes: var_completedBytes,
      totalBytes: var_totalBytes,
      currentFile: var_currentFile,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  GpuDeviceDto sse_decode_gpu_device_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ordinal = sse_decode_u_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_memoryBytes = sse_decode_u_64(deserializer);
    return GpuDeviceDto(
      ordinal: var_ordinal,
      name: var_name,
      memoryBytes: var_memoryBytes,
    );
  }

  @protected
  InstallProgressDto sse_decode_install_progress_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_completedBytes = sse_decode_u_64(deserializer);
    var var_totalBytes = sse_decode_u_64(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return InstallProgressDto(
      completedBytes: var_completedBytes,
      totalBytes: var_totalBytes,
      error: var_error,
    );
  }

  @protected
  List<BackendDto> sse_decode_list_backend_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BackendDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_backend_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<GpuDeviceDto> sse_decode_list_gpu_device_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GpuDeviceDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_gpu_device_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<ModelPathDto> sse_decode_list_model_path_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ModelPathDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_model_path_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<TranscriptLineDto> sse_decode_list_transcript_line_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TranscriptLineDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_transcript_line_dto(deserializer));
    }
    return ans_;
  }

  @protected
  LoadedProjectDto sse_decode_loaded_project_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_audioPath = sse_decode_String(deserializer);
    var var_audioExists = sse_decode_bool(deserializer);
    var var_lineCount = sse_decode_u_32(deserializer);
    return LoadedProjectDto(
      audioPath: var_audioPath,
      audioExists: var_audioExists,
      lineCount: var_lineCount,
    );
  }

  @protected
  ModelPathDto sse_decode_model_path_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_label = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_present = sse_decode_bool(deserializer);
    var var_optional = sse_decode_bool(deserializer);
    return ModelPathDto(
      label: var_label,
      path: var_path,
      present: var_present,
      optional: var_optional,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DownloadProgressDto? sse_decode_opt_box_autoadd_download_progress_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_download_progress_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  SettingsDto sse_decode_settings_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_source = sse_decode_String(deserializer);
    var var_language = sse_decode_String(deserializer);
    var var_backend = sse_decode_String(deserializer);
    var var_deviceOrdinal = sse_decode_u_32(deserializer);
    var var_acppQ8 = sse_decode_bool(deserializer);
    var var_diarization = sse_decode_bool(deserializer);
    var var_diarSpeakers = sse_decode_u_32(deserializer);
    var var_llmPolish = sse_decode_bool(deserializer);
    var var_llmUrl = sse_decode_String(deserializer);
    var var_llmKey = sse_decode_String(deserializer);
    var var_llmModel = sse_decode_String(deserializer);
    var var_mirrorBase = sse_decode_String(deserializer);
    var var_proxy = sse_decode_String(deserializer);
    return SettingsDto(
      source: var_source,
      language: var_language,
      backend: var_backend,
      deviceOrdinal: var_deviceOrdinal,
      acppQ8: var_acppQ8,
      diarization: var_diarization,
      diarSpeakers: var_diarSpeakers,
      llmPolish: var_llmPolish,
      llmUrl: var_llmUrl,
      llmKey: var_llmKey,
      llmModel: var_llmModel,
      mirrorBase: var_mirrorBase,
      proxy: var_proxy,
    );
  }

  @protected
  SystemInfoDto sse_decode_system_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalMemoryBytes = sse_decode_u_64(deserializer);
    var var_cpuCount = sse_decode_u_32(deserializer);
    var var_cpuBrand = sse_decode_String(deserializer);
    var var_backends = sse_decode_list_backend_dto(deserializer);
    return SystemInfoDto(
      totalMemoryBytes: var_totalMemoryBytes,
      cpuCount: var_cpuCount,
      cpuBrand: var_cpuBrand,
      backends: var_backends,
    );
  }

  @protected
  TranscribeEventDto sse_decode_transcribe_event_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_opt_String(deserializer);
    var var_status = sse_decode_opt_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    var var_cancelled = sse_decode_bool(deserializer);
    var var_done = sse_decode_bool(deserializer);
    var var_language = sse_decode_String(deserializer);
    var var_elapsedSec = sse_decode_f_64(deserializer);
    return TranscribeEventDto(
      text: var_text,
      status: var_status,
      error: var_error,
      cancelled: var_cancelled,
      done: var_done,
      language: var_language,
      elapsedSec: var_elapsedSec,
    );
  }

  @protected
  TranscriptLineDto sse_decode_transcript_line_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_startSec = sse_decode_f_64(deserializer);
    var var_endSec = sse_decode_f_64(deserializer);
    var var_speaker = sse_decode_opt_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    return TranscriptLineDto(
      startSec: var_startSec,
      endSec: var_endSec,
      speaker: var_speaker,
      text: var_text,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_download_event_dto_Sse(
    RustStreamSink<DownloadEventDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_download_event_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_install_progress_dto_Sse(
    RustStreamSink<InstallProgressDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_install_progress_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_transcribe_event_dto_Sse(
    RustStreamSink<TranscribeEventDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_transcribe_event_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_backend_dto(BackendDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_bool(self.available, serializer);
    sse_encode_String(self.note, serializer);
    sse_encode_list_gpu_device_dto(self.devices, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_download_progress_dto(
    DownloadProgressDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_download_progress_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_settings_dto(
    SettingsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_settings_dto(self, serializer);
  }

  @protected
  void sse_encode_download_event_dto(
    DownloadEventDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_download_progress_dto(self.progress, serializer);
    sse_encode_opt_String(self.error, serializer);
    sse_encode_bool(self.cancelled, serializer);
  }

  @protected
  void sse_encode_download_progress_dto(
    DownloadProgressDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.completedFiles, serializer);
    sse_encode_u_32(self.totalFiles, serializer);
    sse_encode_u_64(self.completedBytes, serializer);
    sse_encode_u_64(self.totalBytes, serializer);
    sse_encode_String(self.currentFile, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_gpu_device_dto(GpuDeviceDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.ordinal, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_u_64(self.memoryBytes, serializer);
  }

  @protected
  void sse_encode_install_progress_dto(
    InstallProgressDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.completedBytes, serializer);
    sse_encode_u_64(self.totalBytes, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_list_backend_dto(
    List<BackendDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_backend_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_gpu_device_dto(
    List<GpuDeviceDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_gpu_device_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_model_path_dto(
    List<ModelPathDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_model_path_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_transcript_line_dto(
    List<TranscriptLineDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_transcript_line_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_loaded_project_dto(
    LoadedProjectDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.audioPath, serializer);
    sse_encode_bool(self.audioExists, serializer);
    sse_encode_u_32(self.lineCount, serializer);
  }

  @protected
  void sse_encode_model_path_dto(ModelPathDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_bool(self.present, serializer);
    sse_encode_bool(self.optional, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_download_progress_dto(
    DownloadProgressDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_download_progress_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_settings_dto(SettingsDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.source, serializer);
    sse_encode_String(self.language, serializer);
    sse_encode_String(self.backend, serializer);
    sse_encode_u_32(self.deviceOrdinal, serializer);
    sse_encode_bool(self.acppQ8, serializer);
    sse_encode_bool(self.diarization, serializer);
    sse_encode_u_32(self.diarSpeakers, serializer);
    sse_encode_bool(self.llmPolish, serializer);
    sse_encode_String(self.llmUrl, serializer);
    sse_encode_String(self.llmKey, serializer);
    sse_encode_String(self.llmModel, serializer);
    sse_encode_String(self.mirrorBase, serializer);
    sse_encode_String(self.proxy, serializer);
  }

  @protected
  void sse_encode_system_info_dto(
    SystemInfoDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.totalMemoryBytes, serializer);
    sse_encode_u_32(self.cpuCount, serializer);
    sse_encode_String(self.cpuBrand, serializer);
    sse_encode_list_backend_dto(self.backends, serializer);
  }

  @protected
  void sse_encode_transcribe_event_dto(
    TranscribeEventDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.text, serializer);
    sse_encode_opt_String(self.status, serializer);
    sse_encode_opt_String(self.error, serializer);
    sse_encode_bool(self.cancelled, serializer);
    sse_encode_bool(self.done, serializer);
    sse_encode_String(self.language, serializer);
    sse_encode_f_64(self.elapsedSec, serializer);
  }

  @protected
  void sse_encode_transcript_line_dto(
    TranscriptLineDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.startSec, serializer);
    sse_encode_f_64(self.endSec, serializer);
    sse_encode_opt_String(self.speaker, serializer);
    sse_encode_String(self.text, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
