// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `metal_devices`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

Future<SystemInfoDto> systemInfo() =>
    RustLib.instance.api.crateApiDevicesSystemInfo();

class BackendDto {
  /// "cpu" | "metal" | "vulkan"
  final String id;

  /// 展示名，如 "CPU"、"Metal (Apple)"
  final String label;
  final bool available;

  /// 不可用时的说明。
  final String note;
  final List<GpuDeviceDto> devices;

  const BackendDto({
    required this.id,
    required this.label,
    required this.available,
    required this.note,
    required this.devices,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      available.hashCode ^
      note.hashCode ^
      devices.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackendDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          available == other.available &&
          note == other.note &&
          devices == other.devices;
}

class GpuDeviceDto {
  final int ordinal;
  final String name;
  final BigInt memoryBytes;

  const GpuDeviceDto({
    required this.ordinal,
    required this.name,
    required this.memoryBytes,
  });

  @override
  int get hashCode => ordinal.hashCode ^ name.hashCode ^ memoryBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GpuDeviceDto &&
          runtimeType == other.runtimeType &&
          ordinal == other.ordinal &&
          name == other.name &&
          memoryBytes == other.memoryBytes;
}

class SystemInfoDto {
  final BigInt totalMemoryBytes;
  final int cpuCount;
  final String cpuBrand;
  final List<BackendDto> backends;

  const SystemInfoDto({
    required this.totalMemoryBytes,
    required this.cpuCount,
    required this.cpuBrand,
    required this.backends,
  });

  @override
  int get hashCode =>
      totalMemoryBytes.hashCode ^
      cpuCount.hashCode ^
      cpuBrand.hashCode ^
      backends.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SystemInfoDto &&
          runtimeType == other.runtimeType &&
          totalMemoryBytes == other.totalMemoryBytes &&
          cpuCount == other.cpuCount &&
          cpuBrand == other.cpuBrand &&
          backends == other.backends;
}
