// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_source`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// 启动下载（后台线程），进度与终态经 `sink` 推送。
Stream<DownloadEventDto> downloadModel({required String source}) =>
    RustLib.instance.api.crateApiDownloadDownloadModel(source: source);

Future<void> cancelDownload() =>
    RustLib.instance.api.crateApiDownloadCancelDownload();

class DownloadEventDto {
  /// 进行中事件。
  final DownloadProgressDto? progress;

  /// 终态：失败信息。
  final String? error;

  /// 终态：用户取消。
  final bool cancelled;

  const DownloadEventDto({this.progress, this.error, required this.cancelled});

  @override
  int get hashCode => progress.hashCode ^ error.hashCode ^ cancelled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadEventDto &&
          runtimeType == other.runtimeType &&
          progress == other.progress &&
          error == other.error &&
          cancelled == other.cancelled;
}

class DownloadProgressDto {
  final int completedFiles;
  final int totalFiles;
  final BigInt completedBytes;
  final BigInt totalBytes;
  final String currentFile;

  const DownloadProgressDto({
    required this.completedFiles,
    required this.totalFiles,
    required this.completedBytes,
    required this.totalBytes,
    required this.currentFile,
  });

  @override
  int get hashCode =>
      completedFiles.hashCode ^
      totalFiles.hashCode ^
      completedBytes.hashCode ^
      totalBytes.hashCode ^
      currentFile.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadProgressDto &&
          runtimeType == other.runtimeType &&
          completedFiles == other.completedFiles &&
          totalFiles == other.totalFiles &&
          completedBytes == other.completedBytes &&
          totalBytes == other.totalBytes &&
          currentFile == other.currentFile;
}
