// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `acpp_backend_name`, `acpp_transcribe_thread`, `align_pcm`, `diar_bundle_pending_bytes`, `engine`, `find_audiocpp_gguf`, `hybrid_diarize`, `rebuild_exports_from_lines`, `set_proof_lines`, `spawn_install`, `speaker_label`, `speaker_names`, `sync_lines_from_proof`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DiarTurn`, `LinePiece`, `ProjectFile`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<void> loadModel({required String backend, required int deviceOrdinal}) =>
    RustLib.instance.api.crateApiEngineLoadModel(
      backend: backend,
      deviceOrdinal: deviceOrdinal,
    );

Future<void> cancelLoad() => RustLib.instance.api.crateApiEngineCancelLoad();

Future<void> unloadModel() => RustLib.instance.api.crateApiEngineUnloadModel();

Future<bool> isModelLoaded() =>
    RustLib.instance.api.crateApiEngineIsModelLoaded();

Stream<TranscribeEventDto> transcribeFile({
  required String path,
  required String language,
}) => RustLib.instance.api.crateApiEngineTranscribeFile(
  path: path,
  language: language,
);

/// 说话人分离模型是否已就绪（sortformer 分段 + CAM++ 声纹；声纹随包优先）。
Future<bool> diarModelAvailable() =>
    RustLib.instance.api.crateApiEngineDiarModelAvailable();

/// 安装说话人分离模型组合（sortformer ~175MB + CAM++ ~27MB），
/// 字节级进度经 `sink` 推送（后台线程，错误以 error 字段终态上报）。
Stream<InstallProgressDto> installDiarModel() =>
    RustLib.instance.api.crateApiEngineInstallDiarModel();

/// 词级对齐模型是否已安装（可选增强，~1.1 GB）。
Future<bool> alignerModelAvailable() =>
    RustLib.instance.api.crateApiEngineAlignerModelAvailable();

/// 安装词级对齐模型（qwen3_forced_aligner Q8 ~1.1GB，hf-mirror），
/// 字节级进度经 `sink` 推送。
Stream<InstallProgressDto> installAlignerModel() =>
    RustLib.instance.api.crateApiEngineInstallAlignerModel();

/// 最近一次转写的 SRT 字幕（无则空串）。
Future<String> lastSrt() => RustLib.instance.api.crateApiEngineLastSrt();

/// 最近一次转写的 LRC 歌词（无则空串）。
Future<String> lastLrc() => RustLib.instance.api.crateApiEngineLastLrc();

/// 校对视图：带时间轴的文本行（高亮/点行跳转/导出同源）。
Future<List<TranscriptLineDto>> transcriptLines() =>
    RustLib.instance.api.crateApiEngineTranscriptLines();

/// 校对行编辑：更新第 idx 行文本并重建 SRT/LRC（导出反映校对结果）。
/// 文本编辑不改动锚点（对后续拆分而言是近似值，可接受）。
Future<void> updateTranscriptLine({required int index, required String text}) =>
    RustLib.instance.api.crateApiEngineUpdateTranscriptLine(
      index: index,
      text: text,
    );

/// 行级改说话人（diar 精度人工修正）。
Future<void> updateLineSpeaker({required int index, String? speaker}) => RustLib
    .instance
    .api
    .crateApiEngineUpdateLineSpeaker(index: index, speaker: speaker);

/// 压入当前行快照（Dart 在每次修改性操作——拆行/换说话人/防抖文本回写
/// 的每个编辑会话——之前调用）。
Future<void> pushProofSnapshot() =>
    RustLib.instance.api.crateApiEnginePushProofSnapshot();

/// 撤销上一次校准操作：恢复最近快照（行/锚点/说话人整体回滚，跨行
/// 生效——TextField 内置的单行 undo 与此天然分层：其栈空时按键穿透）。
/// 栈空返回 false。
Future<bool> undoProofEdit() =>
    RustLib.instance.api.crateApiEngineUndoProofEdit();

/// 校准模式拆行：在第 index 行的 char_pos（Unicode 字符数，即光标处）
/// 拆为两行——分界时刻**吸附逐字锚点**（qwen3_forced_aligner 的真实字时刻，
/// 锚点间线性插值；无锚点退回字符比例），后半行挂 second_speaker。
Future<void> splitTranscriptLine({
  required int index,
  required int charPos,
  String? secondSpeaker,
}) => RustLib.instance.api.crateApiEngineSplitTranscriptLine(
  index: index,
  charPos: charPos,
  secondSpeaker: secondSpeaker,
);

/// 说话人重命名（如 SPEAKER_00 → "客服"；全局生效，导出同步）。
Future<void> setSpeakerName({required String speaker, required String name}) =>
    RustLib.instance.api.crateApiEngineSetSpeakerName(
      speaker: speaker,
      name: name,
    );

/// 保存项目到指定路径（.asrproj）。当前无校准内容时返回错误。
Future<void> saveProject({required String path}) =>
    RustLib.instance.api.crateApiEngineSaveProject(path: path);

/// 加载项目：恢复行/锚点/原行快照/说话人名到当前会话（SRT/LRC 同步重建）。
Future<LoadedProjectDto> loadProject({required String path}) =>
    RustLib.instance.api.crateApiEngineLoadProject(path: path);

/// 项目加载后音频移动/重选时改指（保存项目时记录新路径）。
Future<void> updateProjectAudio({required String path}) =>
    RustLib.instance.api.crateApiEngineUpdateProjectAudio(path: path);

/// 逐行重新对齐当前项目：从 LAST_AUDIO_PATH 重新解码音频，对 LAST_PROOF
/// 每行（含编辑过的文本）重跑词级对齐——锚点重建、行起止精修。
/// 返回成功对齐的行数。需要对齐模型与已检测的语言（项目或转写记录）。
Future<int> realignProjectLines() =>
    RustLib.instance.api.crateApiEngineRealignProjectLines();

/// 说话人显示名（项目加载后 UI 同步用）。
Future<Map<String, String>> speakerNamesMap() =>
    RustLib.instance.api.crateApiEngineSpeakerNamesMap();

/// 转写完成时的原始行快照（退出校准 diff 基准；项目加载后恢复）。
Future<List<TranscriptLineDto>> originalTranscriptLines() =>
    RustLib.instance.api.crateApiEngineOriginalTranscriptLines();

/// 校对视图：波形峰值（0..1，每秒 buckets 个），按路径缓存。
Future<Float32List> waveformPeaks({
  required String path,
  required int bucketsPerSec,
}) => RustLib.instance.api.crateApiEngineWaveformPeaks(
  path: path,
  bucketsPerSec: bucketsPerSec,
);

/// 外接 LLM 润色（OpenAI 兼容端点，配置见设置）。失败返回 Err，
/// 调用方保留原文并提示。
Future<String> polishText({required String text}) =>
    RustLib.instance.api.crateApiEnginePolishText(text: text);

Future<void> stopTranscribe() =>
    RustLib.instance.api.crateApiEngineStopTranscribe();

/// Q8 模型是否已生成（设置页状态展示）。
Future<bool> q8ModelAvailable() =>
    RustLib.instance.api.crateApiEngineQ8ModelAvailable();

/// 一键转换：-hf safetensors → audio.cpp 方言 Q8 GGUF（model.q8_0.gguf）。
/// 调用随应用分发的 audiocpp_gguf 工具（AppImage usr/bin 内），约 10 秒。
Future<void> convertModelToQ8() =>
    RustLib.instance.api.crateApiEngineConvertModelToQ8();

/// 模型安装进度（字节级；error 非空 = 终态失败）。
class InstallProgressDto {
  final BigInt completedBytes;
  final BigInt totalBytes;
  final String? error;

  const InstallProgressDto({
    required this.completedBytes,
    required this.totalBytes,
    this.error,
  });

  @override
  int get hashCode =>
      completedBytes.hashCode ^ totalBytes.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InstallProgressDto &&
          runtimeType == other.runtimeType &&
          completedBytes == other.completedBytes &&
          totalBytes == other.totalBytes &&
          error == other.error;
}

/// 加载项目的结果（音频存在性由调用方处理提示与重选）。
class LoadedProjectDto {
  final String audioPath;
  final bool audioExists;
  final int lineCount;

  const LoadedProjectDto({
    required this.audioPath,
    required this.audioExists,
    required this.lineCount,
  });

  @override
  int get hashCode =>
      audioPath.hashCode ^ audioExists.hashCode ^ lineCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoadedProjectDto &&
          runtimeType == other.runtimeType &&
          audioPath == other.audioPath &&
          audioExists == other.audioExists &&
          lineCount == other.lineCount;
}

class TranscribeEventDto {
  /// 当前累计转写全文（流式每步更新，替换式）。
  final String? text;

  /// 过程状态（如「正在精修时间轴… 3/87」）；UI 进度文案用。
  final String? status;

  /// 终态：失败信息。
  final String? error;

  /// 终态：用户取消（text 事件已含部分结果）。
  final bool cancelled;

  /// 终态：正常完成。
  final bool done;
  final String language;
  final double elapsedSec;

  const TranscribeEventDto({
    this.text,
    this.status,
    this.error,
    required this.cancelled,
    required this.done,
    required this.language,
    required this.elapsedSec,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      status.hashCode ^
      error.hashCode ^
      cancelled.hashCode ^
      done.hashCode ^
      language.hashCode ^
      elapsedSec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranscribeEventDto &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          status == other.status &&
          error == other.error &&
          cancelled == other.cancelled &&
          done == other.done &&
          language == other.language &&
          elapsedSec == other.elapsedSec;
}

/// 校对视图的带时间轴文本行（SRT/LRC 同源切分）。
class TranscriptLineDto {
  final double startSec;
  final double endSec;

  /// 说话人（diar 开启时），如 "SPEAKER_00"
  final String? speaker;
  final String text;

  const TranscriptLineDto({
    required this.startSec,
    required this.endSec,
    this.speaker,
    required this.text,
  });

  @override
  int get hashCode =>
      startSec.hashCode ^ endSec.hashCode ^ speaker.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranscriptLineDto &&
          runtimeType == other.runtimeType &&
          startSec == other.startSec &&
          endSec == other.endSec &&
          speaker == other.speaker &&
          text == other.text;
}
