// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 模型快照缓存目录（跨平台，见 asr_core::model::models_root）。
Future<String> modelDirPath() =>
    RustLib.instance.api.crateApiModelModelDirPath();

/// 目录是否已有完整可加载的快照：config.json + tokenizer.json + 非空
/// model.safetensors。镜像 Swift 版 ModelDownloader.isCached 的判定。
Future<bool> modelIsOnDisk() =>
    RustLib.instance.api.crateApiModelModelIsOnDisk();

/// 全部使用中的模型路径（ASR 主体 + Q8 + 说话人分离两件 + 词级对齐）。
Future<List<ModelPathDto>> modelPaths() =>
    RustLib.instance.api.crateApiModelModelPaths();

/// 设置页展示用的模型条目（路径 + 在盘状态）。
class ModelPathDto {
  final String label;
  final String path;
  final bool present;

  /// 可选组件（未安装不算异常，仅提示）
  final bool optional;

  const ModelPathDto({
    required this.label,
    required this.path,
    required this.present,
    required this.optional,
  });

  @override
  int get hashCode =>
      label.hashCode ^ path.hashCode ^ present.hashCode ^ optional.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelPathDto &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          path == other.path &&
          present == other.present &&
          optional == other.optional;
}
