// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<SettingsDto> loadSettings() =>
    RustLib.instance.api.crateApiSettingsLoadSettings();

Future<void> saveSettings({required SettingsDto dto}) =>
    RustLib.instance.api.crateApiSettingsSaveSettings(dto: dto);

class SettingsDto {
  /// "modelScope" | "huggingFace"
  final String source;

  /// 语言 id，"auto" = 自动检测
  final String language;

  /// "auto" | "cpu" | "metal" | "vulkan"
  final String backend;
  final int deviceOrdinal;

  /// audiocpp 引擎是否用 Q8 量化模型
  final bool acppQ8;

  /// 说话人分离（需 sherpa 模型）
  final bool diarization;

  /// 已知说话人数（0=自动聚类）
  final int diarSpeakers;

  /// 外接 LLM 润色（OpenAI 兼容端点）
  final bool llmPolish;
  final String llmUrl;
  final String llmKey;
  final String llmModel;

  /// HF 类下载镜像基址（空 = 按下载源默认）
  final String mirrorBase;

  /// 网络代理 http/https/socks5/socks5h（空 = 不使用）
  final String proxy;

  const SettingsDto({
    required this.source,
    required this.language,
    required this.backend,
    required this.deviceOrdinal,
    required this.acppQ8,
    required this.diarization,
    required this.diarSpeakers,
    required this.llmPolish,
    required this.llmUrl,
    required this.llmKey,
    required this.llmModel,
    required this.mirrorBase,
    required this.proxy,
  });

  @override
  int get hashCode =>
      source.hashCode ^
      language.hashCode ^
      backend.hashCode ^
      deviceOrdinal.hashCode ^
      acppQ8.hashCode ^
      diarization.hashCode ^
      diarSpeakers.hashCode ^
      llmPolish.hashCode ^
      llmUrl.hashCode ^
      llmKey.hashCode ^
      llmModel.hashCode ^
      mirrorBase.hashCode ^
      proxy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettingsDto &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          language == other.language &&
          backend == other.backend &&
          deviceOrdinal == other.deviceOrdinal &&
          acppQ8 == other.acppQ8 &&
          diarization == other.diarization &&
          diarSpeakers == other.diarSpeakers &&
          llmPolish == other.llmPolish &&
          llmUrl == other.llmUrl &&
          llmKey == other.llmKey &&
          llmModel == other.llmModel &&
          mirrorBase == other.mirrorBase &&
          proxy == other.proxy;
}
